version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: chain-command-app-php
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "PHPSTORM"
      XDEBUG_CONFIG: "client_port=9003 client_host=172.19.0.1 max_nesting_level=1000 log_level=0"
      PHP_IDE_CONFIG: serverName=docker.local
    volumes:
      - ./app:/var/www/chain-command
